// lib/destinationMap.ts

export const destinationMap = {
    'anse-saint-jean': {
        label: 'Anse Saint Jean',
        blogUrl: '/blog/anse-saint-jean',
        videoUrl: '/videos#anse-saint-jean',
        objectsUrl: '/objets',
        plannerUrl: '/planificateur',
    },
    'baie-saint-paul': {
        label: 'Baie Saint Paul',
        blogUrl: '/blog/baie-saint-paul',
        videoUrl: '/videos#baie-saint-paul',
        objectsUrl: '/objets',
        plannerUrl: '/planificateur',
    },
    'bic': {
        label: 'Bic',
        blogUrl: '/blog/bic',
        videoUrl: '/videos#bic',
        objectsUrl: '/objets',
        plannerUrl: '/planificateur',
    },
    'bromont-granby': {
        label: 'Bromont Granby',
        blogUrl: '/blog/bromont-granby',
        videoUrl: '/videos#bromont-granby',
        objectsUrl: '/objets',
        plannerUrl: '/planificateur',
    },
    'canyon': {
        label: 'Canyon',
        blogUrl: '/blog/canyon',
        videoUrl: '/videos#canyon',
        objectsUrl: '/objets',
        plannerUrl: '/planificateur',
    },
    'carleton': {
        label: 'Carleton',
        blogUrl: '/blog/carleton',
        videoUrl: '/videos#carleton',
        objectsUrl: '/objets',
        plannerUrl: '/planificateur',
    },
    'eeyou-istchee': {
        label: 'Eeyou Istchee',
        blogUrl: '/blog/eeyou-istchee',
        videoUrl: '/videos#eeyou-istchee',
        objectsUrl: '/objets',
        plannerUrl: '/planificateur',
    },
    'forillon': {
        label: 'Forillon',
        blogUrl: '/blog/forillon',
        videoUrl: '/videos#forillon',
        objectsUrl: '/objets',
        plannerUrl: '/planificateur',
    },
    'gaspesie': {
        label: 'Gaspesie',
        blogUrl: '/blog/gaspesie',
        videoUrl: '/videos#gaspesie',
        objectsUrl: '/objets',
        plannerUrl: '/planificateur',
    },
    'grand-bend': {
        label: 'Grand Bend',
        blogUrl: '/blog/grand-bend',
        videoUrl: '/videos#grand-bend',
        objectsUrl: '/objets',
        plannerUrl: '/planificateur',
    },
    'hautes-gorges': {
        label: 'Hautes Gorges',
        blogUrl: '/blog/hautes-gorges',
        videoUrl: '/videos#hautes-gorges',
        objectsUrl: '/objets',
        plannerUrl: '/planificateur',
    },
    'kamouraska': {
        label: 'Kamouraska',
        blogUrl: '/blog/kamouraska',
        videoUrl: '/videos#kamouraska',
        objectsUrl: '/objets',
        plannerUrl: '/planificateur',
    },
    'kuururjuaq': {
        label: 'Kuururjuaq',
        blogUrl: '/blog/kuururjuaq',
        videoUrl: '/videos#kuururjuaq',
        objectsUrl: '/objets',
        plannerUrl: '/planificateur',
    },
    'levis': {
        label: 'Levis',
        blogUrl: '/blog/levis',
        videoUrl: '/videos#levis',
        objectsUrl: '/objets',
        plannerUrl: '/planificateur',
    },
    'locationvr': {
        label: 'LocationVR',
        blogUrl: '/blog/locationvr',
        videoUrl: '/videos#locationvr',
        objectsUrl: '/objets',
        plannerUrl: '/planificateur',
    },
    'magog-orford': {
        label: 'Magog Orford',
        blogUrl: '/blog/magog-orford',
        videoUrl: '/videos#magog-orford',
        objectsUrl: '/objets',
        plannerUrl: '/planificateur',
    },
    'massif': {
        label: 'Massif',
        blogUrl: '/blog/massif',
        videoUrl: '/videos#massif',
        objectsUrl: '/objets',
        plannerUrl: '/planificateur',
    },
    'mingan': {
        label: 'Mingan',
        blogUrl: '/blog/mingan',
        videoUrl: '/videos#mingan',
        objectsUrl: '/objets',
        plannerUrl: '/planificateur',
    },
    'montmorency': {
        label: 'Montmorency',
        blogUrl: '/blog/montmorency',
        videoUrl: '/videos#montmorency',
        objectsUrl: '/objets',
        plannerUrl: '/planificateur',
    },
    'montreal': {
        label: 'Montreal',
        blogUrl: '/blog/montreal',
        videoUrl: '/videos#montreal',
        objectsUrl: '/objets',
        plannerUrl: '/planificateur',
    },
    'orleans': {
        label: 'Orleans',
        blogUrl: '/blog/orleans',
        videoUrl: '/videos#orleans',
        objectsUrl: '/objets',
        plannerUrl: '/planificateur',
    },
    'perce': {
        label: 'Perce',
        blogUrl: '/blog/perce',
        videoUrl: '/videos#perce',
        objectsUrl: '/objets',
        plannerUrl: '/planificateur',
    },
    'port-au-persil': {
        label: 'Port au Persil',
        blogUrl: '/blog/port-au-persil',
        videoUrl: '/videos#port-au-persil',
        objectsUrl: '/objets',
        plannerUrl: '/planificateur',
    },
    'port-cartier': {
        label: 'Port Cartier',
        blogUrl: '/blog/port-cartier',
        videoUrl: '/videos#port-cartier',
        objectsUrl: '/objets',
        plannerUrl: '/planificateur',
    },
    'port-dover': {
        label: 'Port Dover',
        blogUrl: '/blog/port-dover',
        videoUrl: '/videos#port-dover',
        objectsUrl: '/objets',
        plannerUrl: '/planificateur',
    },
    'quebec': {
        label: 'Quebec',
        blogUrl: '/blog/quebec',
        videoUrl: '/videos#quebec',
        objectsUrl: '/objets',
        plannerUrl: '/planificateur',
    },
    'rivieredu-loup': {
        label: 'Rivieredu Loup',
        blogUrl: '/blog/rivieredu-loup',
        videoUrl: '/videos#rivieredu-loup',
        objectsUrl: '/objets',
        plannerUrl: '/planificateur',
    },
    'sabrevois': {
        label: 'Sabrevois',
        blogUrl: '/blog/sabrevois',
        videoUrl: '/videos#sabrevois',
        objectsUrl: '/objets',
        plannerUrl: '/planificateur',
    },
    'sandbanks': {
        label: 'Sandbanks',
        blogUrl: '/blog/sandbanks',
        videoUrl: '/videos#sandbanks',
        objectsUrl: '/objets',
        plannerUrl: '/planificateur',
    },
    'sauble-beach': {
        label: 'Sauble Beach',
        blogUrl: '/blog/sauble-beach',
        videoUrl: '/videos#sauble-beach',
        objectsUrl: '/objets',
        plannerUrl: '/planificateur',
    },
    'sept-iles': {
        label: 'Sept Iles',
        blogUrl: '/blog/sept-iles',
        videoUrl: '/videos#sept-iles',
        objectsUrl: '/objets',
        plannerUrl: '/planificateur',
    },
    'sherbrooke': {
        label: 'Sherbrooke',
        blogUrl: '/blog/sherbrooke',
        videoUrl: '/videos#sherbrooke',
        objectsUrl: '/objets',
        plannerUrl: '/planificateur',
    },
    'singing-sands': {
        label: 'Singing Sands',
        blogUrl: '/blog/singing-sands',
        videoUrl: '/videos#singing-sands',
        objectsUrl: '/objets',
        plannerUrl: '/planificateur',
    },
    'tadoussac': {
        label: 'Tadoussac',
        blogUrl: '/blog/tadoussac',
        videoUrl: '/videos#tadoussac',
        objectsUrl: '/objets',
        plannerUrl: '/planificateur',
    },
    'wasaga-beach': {
        label: 'Wasaga Beach',
        blogUrl: '/blog/wasaga-beach',
        videoUrl: '/videos#wasaga-beach',
        objectsUrl: '/objets',
        plannerUrl: '/planificateur',
    },
};

