onlyBuiltDependencies:
  - bufferutil
  - core-js
  - esbuild
  - puppeteer
  - sharp
  - unrs-resolver
  - utf-8-validate

overrides:
  axios@>=0.8.1 <0.28.0: '>=0.28.0'
  axios@<0.30.0: '>=0.30.0'
  form-data@>=4.0.0 <4.0.4: '>=4.0.4'
  form-data@>=3.0.0 <3.0.4: '>=3.0.4'
  next@>=0.9.9 <14.2.31: '>=14.2.31'
  jspdf@<=3.0.1: '>=3.0.2'
  next@>=0.9.9 <14.2.32: '>=14.2.32'
  axios@<0.30.2: '>=0.30.2'
  axios@>=1.0.0 <1.12.0: '>=1.12.0'
  tar-fs@>=3.0.0 <3.1.1: '>=3.1.1'
